# Generated by Django 5.2.4 on 2025-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_student_times_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='end_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
