# Generated by Django 5.2.4 on 2025-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_timeslot_end_minutes_timeslot_start_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='autodrom_hours',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='student',
            name='city_hours',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='teacher',
            name='friday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='monday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='saturday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sunday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='thursday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tuesday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='wednesday_free_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='times_per_week',
            field=models.IntegerField(default=3),
        ),
    ]
