# Generated by Django 5.2.4 on 2025-07-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_student_autodrom_hours_student_city_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
