# Generated by Django 5.2.4 on 2025-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_lesson_is_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(blank=True, choices=[('autodrom', 'Автодром'), ('city', 'Город'), ('', 'Не выбрано')], default='', max_length=10),
        ),
    ]
