# Generated by Django 5.2.4 on 2025-07-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_student_user_teacher_user_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
