# Generated by Django 5.2.4 on 2025-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_alter_student_subject_alter_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
