# Generated by Django 5.2.4 on 2025-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_lesson_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
