# Generated by Django 5.2.4 on 2025-07-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_lesson_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_attended',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'scheduled'), (1, 'confirmed'), (2, 'attended'), (3, 'cancelled')], default=0),
        ),
    ]
