# Generated by Django 5.2.4 on 2025-07-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0022_remove_lesson_is_attended_remove_lesson_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
