# Generated by Django 5.2.4 on 2025-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_lesson_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(choices=[(0, 'Запланировано'), (1, 'Подтверждено'), (2, 'Посещено'), (3, 'Отменено')], default=0),
        ),
    ]
